name: Update README Progress

on:
  push:
    branches:
      - maingit 

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count solved problems
        run: |
          echo "Contando problemas..."
